# @host=http://localhost:7071

@host=https://func-api-cszcveypxkw6i.azurewebsites.net/


### Ask what the weather is in a place to trigger GetWeather function
POST  {{host}}/api/prompt
Content-Type: application/json

{
    "Prompt": "What is 2+2? and 2/22 and 2-2"
}
